name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Create config file
        run: sudo mkdir -p /etc/opt/mazlite
      - name: Print goodbye
        run: echo "Done - bye!"
